### ISSUE TITLE
Bác mình hỏi có dùng được iGPU ko bác?

### ISSUE THREAD

**Issue by hoangphison** [chiendo97/hackintosh-asrock-b365-itx-ac-opencore#1]
Hello bác, e đang tính build 1 e cấu hình tương tự như bác, nhưng k dùng GPU rời. bác cho e hỏi config như bác có dùng được iGPU ko hay phải chơi GPU rời. thank bác!

**Comment by chiendo97** [comment]
Chào bác. Có dùng được IGPU của I5-9400 nhé. 
Ngay hiện tại mình đang tháo RX580 ra để dùng IGPU đây.

**Comment by chiendo97** [comment]
Ý quên. Bác chuyển sang branch `igpu` để dùng với igpu nhé.
