### ISSUE TITLE
Bác có Shutdown được máy ko ? 

### ISSUE THREAD

**Issue by thetrung** [chiendo97/hackintosh-asrock-b365-itx-ac-opencore#2]
Mình dùng con main Asrock B365M Pro4-F + spec còn lại giống bác ( 9400F + RX580 ), nhưng mà trên Clover thì đang ko shutdown / sleep bt được. Mấy cái còn lại thì ngon.

Trc cũng thử cài OpenCore 0.5.8 nhưng chả vào nổi =))

**Comment by chiendo97** [comment]
Hi bác. 
Máy mình shutdown / sleep hoàn toàn bình thường nhé. 
Hiện tại OpenCore đã ổn định hơn nhiều rồi, bác chịu khó đọc guide rồi tham khảo config của mình. 
Chúc bác may mắn.

**Comment by thetrung** [comment]
Ok ngon r, giờ mình lên BigSur + OpenCore
