### ISSUE TITLE
mình dùng b365m pro 4 +rx 570 mà k dùng đc ufi này nhỉ?

### ISSUE THREAD

**Issue by ntvsp** [chiendo97/hackintosh-asrock-b365-itx-ac-opencore#3]
chào bạn... mình đã config lại serial uuid các thứ rồi mà k boot đc vào menu của opencore luôn ? :(

**Comment by chiendo97** [comment]
Hi bác. 

Không biết bác đang dùng CPU nào nhỉ? Nếu cũng là Coffee Lake thì mình nghĩ là dùng được config của mình.

**Comment by ntvsp** [comment]
Tks bác. Em cài đc rồi nhwof tham khảo ufi của bác tks. :)
